services:
  - type: web
    name: regellikbot
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: TELEGRAM_AUTH_STRICT
        value: false
      - key: MONGODB_URI
        value: mongodb+srv://malinovskij280584_db_user:6fOXnVQpC6mBCEen@cluster0.gltmfhe.mongodb.net/regellik?retryWrites=true&w=majority&appName=Cluster0