services:
  - type: web
    name: regellikbot
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    customDomains:
      - name: www.regellik.org
      - name: regellik.org
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: TELEGRAM_AUTH_STRICT
        value: false
      - key: MONGODB_URI
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false